apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline2
spec:
  params:
    - name: message
      type: string
      default: "hello from candialane/cicd 0.1"
  tasks:
    - name: say-hello-from-git
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/candialane/cicd.git
          - name: revision
            value: "0.1"
          - name: path
            value: tasks/hello.yaml
      params:
        - name: message
          value: "$(params.message)"
