apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipeline2
spec:
  pipelineSpec:
    params:
      - name: message
        type: string
        default: "hello from git resolver"
    tasks:
      - name: say-hello-from-git
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/candialane/cicd.git
            - name: revision
              value: "0.1"
            - name: path
              value: tasks/hello.yaml
        params:
          - name: message
            value: "$(params.message)"
  params:
    - name: message
      value: "hello from candialane/cicd 0.1"
